In [2]:
import numpy as np
import skimage.util
a = np.arange(1, 7).reshape(2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
b = a * 10

In [7]:
c = a * 100

In [8]:
print(c)

[[100 200 300]
 [400 500 600]]


In [9]:
m = skimage.util.montage([a, b, c])
print(m)

[[  1   2   3  10  20  30]
 [  4   5   6  40  50  60]
 [100 200 300 129 129 129]
 [400 500 600 129 129 129]]


In [10]:
print(m.shape)

(4, 6)


In [11]:
abc = np.array([a, b, c])
print(abc)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [ 40  50  60]]

 [[100 200 300]
  [400 500 600]]]


In [12]:
print(abc.shape)

(3, 2, 3)


In [14]:
print(skimage.util.montage(abc))

[[  1   2   3  10  20  30]
 [  4   5   6  40  50  60]
 [100 200 300 129 129 129]
 [400 500 600 129 129 129]]


In [15]:
d = a[:, :2]
print(d)

[[1 2]
 [4 5]]


In [16]:
print(np.mean(np.array([a, b, c])))

129.5


In [17]:
print(skimage.util.montage([a, b, c], fill=0))

[[  1   2   3  10  20  30]
 [  4   5   6  40  50  60]
 [100 200 300   0   0   0]
 [400 500 600   0   0   0]]


In [18]:
print(skimage.util.montage([a, b, c], grid_shape=(1, 3)))

[[  1   2   3  10  20  30 100 200 300]
 [  4   5   6  40  50  60 400 500 600]]


In [19]:
print(skimage.util.montage([a, b, c], grid_shape=(3, 1)))

[[  1   2   3]
 [  4   5   6]
 [ 10  20  30]
 [ 40  50  60]
 [100 200 300]
 [400 500 600]]


In [20]:
print(skimage.util.montage([a, b, c], grid_shape=(2, 3)))

[[  1   2   3  10  20  30 100 200 300]
 [  4   5   6  40  50  60 400 500 600]
 [129 129 129 129 129 129 129 129 129]
 [129 129 129 129 129 129 129 129 129]]


In [21]:
print(skimage.util.montage([a, b, c], grid_shape=(2, 3), fill=0))

[[  1   2   3  10  20  30 100 200 300]
 [  4   5   6  40  50  60 400 500 600]
 [  0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]]


In [22]:
print(skimage.util.montage([a, b, c], padding_width=1))

[[129 129 129 129 129 129 129 129 129]
 [129   1   2   3 129  10  20  30 129]
 [129   4   5   6 129  40  50  60 129]
 [129 129 129 129 129 129 129 129 129]
 [129 100 200 300 129 129 129 129 129]
 [129 400 500 600 129 129 129 129 129]
 [129 129 129 129 129 129 129 129 129]]


In [24]:
print(skimage.util.montage([a, b, c], padding_width=1, fill=0))

[[  0   0   0   0   0   0   0   0   0]
 [  0   1   2   3   0  10  20  30   0]
 [  0   4   5   6   0  40  50  60   0]
 [  0   0   0   0   0   0   0   0   0]
 [  0 100 200 300   0   0   0   0   0]
 [  0 400 500 600   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0]]


In [25]:
import skimage.io
import skimage.util
a = skimage.io.imread('CR.jpg')
print(a.shape)
b = a // 2
c = a // 3
m = skimage.util.montage([a, b, c], multichannel=True)
print(m.shape)
skimage.io.imsave('D:/Image Processing/MONTAGE.jpg', m)

(800, 1200, 3)
(1600, 2400, 3)


C:\Users\User\AppData\Local\Temp\ipykernel_9680\3327231803.py:7: FutureWarning: `multichannel` is a deprecated argument name for `montage`. It will be removed in version 1.0. Please use `channel_axis` instead.
  m = skimage.util.montage([a, b, c], multichannel=True)


In [26]:
m_1_3_pad = skimage.util.montage([a, b, c],
                                 fill=(0, 0, 0),
                                 grid_shape=(1,3),
                                 padding_width=10,
                                 multichannel=True)
print(m_1_3_pad.shape)

skimage.io.imsave("D:/Image Processing/skimage_montage_1_3_pad.jpg", m_1_3_pad)

(820, 3640, 3)


C:\Users\User\AppData\Local\Temp\ipykernel_9680\130585821.py:1: FutureWarning: `multichannel` is a deprecated argument name for `montage`. It will be removed in version 1.0. Please use `channel_axis` instead.
  m_1_3_pad = skimage.util.montage([a, b, c],
